defaults: &defaults
  working_directory: /tmp/project
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: cibuilds/hugo
    steps:
      - checkout
      - run:
          name: Build
          command: HUGO_ENV=production hugo -v -s src/
      - run:
          name: Test
          command: htmlproofer src/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - store_artifacts:
          path: /tmp/project/src/public
      - persist_to_workspace:
          root: src
          paths:
            - public
  deploy:
    <<: *defaults
    docker:
      - image: amazonlinux:2
    steps:
      - run:
          name: Install AWS CLI
          command: yum install -y awscli tar
      - attach_workspace:
          at: src
      - run:
          name: Deploy
          command: aws s3 sync src/public s3://denniswebb.info --delete --acl public-read 

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
